export type RelatedGameTag =
  | 'paint'
  | 'lobby'
  | 'fps'
  | 'tactics'
  | 'tools'
  | 'companion';

export type RelatedGame = {
  id: string;
  slug: string;
  title: string;
  note: string;
  source: string;
  href: string;
  iframeSrc: string;
  image: string;
  external: boolean;
  tag: RelatedGameTag;
  featured?: boolean;
  demoId?: string;
  description?: string;
  highlights?: string[];
  controls?: { keys: string; action: string }[];
};

const gd = (id: string) => `https://html5.gamedistribution.com/${id}/`;
const gdImg = (id: string) => `/imgs/related-games/${id}.jpg`;

export const relatedGames: RelatedGame[] = [
  {
    id: 'meccha-browser',
    slug: 'meccha-chameleon-browser-game',
    title: 'Meccha Chameleon',
    note:
      'Official Meccha Chameleon Steam artwork with paint, disguise, quick play, room creation, and practice context. The native browser build is in active development — this card links to the in-house play page while we ship it.',
    source: 'Meccha Chameleon Art Studio',
    href: '/meccha-chameleon-browser-game',
    iframeSrc: '',
    image: '/imgs/related-games/meccha-chameleon.png',
    external: false,
    tag: 'paint',
    featured: true,
    demoId: 'easy',
    description:
      'Meccha Chameleon is a paint-and-hide browser game built around one simple idea: blend into the room before the seeker finds you. Start with quick play, create a private room, or practice in the official browser build, then use color, wall texture, shadow, and props to break your silhouette. The best hiding spots are not always the darkest corners; they are places where your body shape disappears into busy furniture, patterned walls, or stacked objects. This card uses official Meccha Chameleon Steam artwork rather than a recycled site screenshot or a different hide-and-seek game thumbnail. The previous third-party embed has been retired while we finish the in-house Meccha Chameleon browser build.',
    highlights: [
      'Official Meccha Chameleon Steam artwork',
      'Paint-and-hide gameplay with quick play and practice',
      'In-house browser build coming soon — no third-party iframe',
      'Image matches the actual game brand shown to users',
    ],
    controls: [
      { keys: 'Quick Start', action: 'Enter a public Meccha Chameleon round' },
      { keys: 'Create Room', action: 'Host a private room for friends' },
      { keys: 'Practice', action: 'Test hiding routes and color matching' },
    ],
  },
  { id: 'hide-n-seek-gd', slug: 'hide-n-seek', title: 'Hide N Seek!', note: 'Classic maze-style hide-and-seek rounds from GameDistribution.', source: 'GameDistribution', href: gd('7eda2be289604aa89f3b97df59661bfe'), iframeSrc: gd('7eda2be289604aa89f3b97df59661bfe'), image: '/imgs/related-games/hide-n-seek-gd.jpeg', external: true, tag: 'lobby', featured: true, description: 'Hide N Seek! drops you into a brightly colored 3D maze full of corridors, gold keys, and a round timer ticking down from the moment the round starts. Each round randomly picks a Seeker while everyone else scrambles for cover; the Seeker has to find and tag the hiders before time runs out, and any hidden player who slips all the way to the exit area scores a big bonus. The map re-randomizes between rounds so the same hiding corner never stays safe twice. Free browser play, no login required, instant respawn on round end. Best runs come from re-painting your avatar with whatever surface texture you plan to camp on — the same idea at the heart of the Meccha Chameleon paint-to-hide loop, just compressed into 60-second browser rounds.', highlights: ['Top-down 3D maze, keyboard or on-screen joystick', 'Round timer with gold keys to collect', 'Re-randomised maps so no spot stays safe twice', 'Compact sessions: 1–3 minutes per round'], controls: [{ keys: 'WASD / Arrows', action: 'Move your character' }, { keys: 'Shift', action: 'Sprint to escape the seeker' }, { keys: 'Space', action: 'Pick up / interact with gold keys' }] },
  { id: 'sneaky-friends', slug: 'sneaky-friends', title: 'Sneaky Friends', note: 'Friend-focused hide-and-seek with a social party-game feel.', source: 'GameDistribution', href: gd('8529938662c2447091414e2cc73983e3'), iframeSrc: gd('8529938662c2447091414e2cc73983e3'), image: '/imgs/related-games/sneaky-friends.jpg', external: true, tag: 'companion', featured: true, demoId: 'social', description: "Sneaky Friends takes the hide-and-seek template and bolts on a social-party-game chassis: short rounds, multiple maps, item pickups that freeze the seeker, and a parade of unlockable costumes that don't change gameplay but absolutely change how loud you feel about your run. The tightest trick is the smoke-grenade pickup — drop it mid-pursuit to break line of sight and slip through a crowded corridor. Single-player against bots works great for practicing routes, but the mode shines when you queue it up with two or three friends because the snow-balling panic once everyone realises a Seeker is running halfway across the map never gets old.", highlights: ['Best played with 2–4 friends on the same screen', 'Smoke grenades, decoys, and freeze pickups', 'Unlockable costumes change the look, not the rules', 'Quick 90-second rounds keep the lobby moving'], controls: [{ keys: 'WASD / Arrows', action: 'Move' }, { keys: 'Click', action: 'Throw smoke grenade or decoy' }, { keys: 'E', action: 'Pick up nearby item' }] },
  { id: 'stickman-hide-seek', slug: 'stickman-hide-and-seek', title: 'Stickman Hide and Seek', note: 'Stickman hide-or-seek with fast, simple controls.', source: 'GameDistribution', href: gd('239942ce1a1349f6bcc9d312b32c5c3b'), iframeSrc: gd('239942ce1a1349f6bcc9d312b32c5c3b'), image: '/imgs/related-games/stickman-hide-seek.jpeg', external: true, tag: 'lobby', featured: true, description: "Stickman Hide and Seek ships the same hide-or-seek loop in a minimalist stick figure style: chunky black outlines, flat colored backgrounds, and movement that snaps the way browser physics games did ten years ago. It's the lowest-stakes entry on this page, which is exactly why it's great when you want a quick round between work blocks. Rounds last about a minute, the Seeker is a single AI, and the winner is decided more by reading the map than by twitch reflexes. A good warm-up for someone who's never played hide-and-seek browser games before.", highlights: ['Stick figure art, very low GPU demand', 'Single-AI Seeker rounds, ~60 seconds each', 'Perfect warm-up or break-time game', 'Works fine on older laptops'], controls: [{ keys: 'WASD / Arrows', action: 'Move your stickman' }, { keys: 'Mouse', action: 'Look around / orient camera' }] },
  { id: 'skibidi-hide-seek', slug: 'skibidi-titans-hide-and-seek', title: 'Skibidi Titans Hide And Seek', note: 'Hunter-versus-escape rounds with a loud chase-game style.', source: 'GameDistribution', href: gd('38d6fc63e63c4be69887a604699c864a'), iframeSrc: gd('38d6fc63e63c4be69887a604699c864a'), image: '/imgs/related-games/skibidi-hide-seek.jpg', external: true, tag: 'companion', featured: true, description: 'Skibidi Titans Hide And Seek leans into the meme-aesthetic side of the genre: oversized heads, loud capcom-style screams, and Seeker characters that chase you with the energy of a Friday-night party game. Underneath the audio it is a competent 3D hide-and-seek — wide interiors, lots of vertical cover, and a generous stamina bar for sprinting through open courtyards. Rounds can get chaotic with five players on screen; that is the point. Best for streamers and creators looking for a chase reaction-clip moment.', highlights: ['Big characters, meme-friendly audio cues', 'Indoor + outdoor maps with multiple floors', 'Stamina and sprint for tense last-second escapes', 'Built to create shareable clutch moments'], controls: [{ keys: 'WASD', action: 'Run' }, { keys: 'Shift', action: 'Burst sprint (uses stamina)' }, { keys: 'Q', action: 'Quick camera look behind you' }] },
  { id: 'horror-escape', slug: 'hide-and-seek-horror-escape', title: 'Hide And Seek: Horror Escape', note: 'A darker hide-and-seek escape game with horror rooms.', source: 'GameDistribution', href: gd('169645f5ac814065968e3872875bbce1'), iframeSrc: gd('169645f5ac814065968e3872875bbce1'), image: '/imgs/related-games/horror-escape.jpg', external: true, tag: 'tactics', featured: true, description: "Hide And Seek: Horror Escape dresses the same hide-and-seek formula in darker tones: low-light hospital and school corridors, ambient creaks, and a Seeker character design that leans into found-footage horror rather than goofy chase-cartoon. It's still a hide-and-seek round, but the tension ramp is real because there are no second chances once tagged and the round can collapse in a single corridor sighting. If you're the kind of player who gets a kick out of breaking a sweat during the final ten seconds of a round, this is the page entry to click first. Single-player vs AI, with quick respawn so you can chain attempts.", highlights: ['Horror-map version of hide-and-seek', 'Single round = single chance (no respawn mid-round)', 'Best for players who want real round tension', 'Includes hospital, school, and basement maps'], controls: [{ keys: 'WASD', action: 'Move quietly' }, { keys: 'Shift', action: 'Walk slowly (less noise)' }, { keys: 'F', action: 'Hide inside locker / cabinet' }] },
  { id: 'kitten-hide-seek', slug: 'kitten-hide-and-seek', title: 'Kitten Hide And Seek', note: 'A cute puzzle hide-and-seek game with simple stealth timing.', source: 'GameDistribution', href: gd('b78553bf5db34812972452aab68f88c0'), iframeSrc: gd('b78553bf5db34812972452aab68f88c0'), image: '/imgs/related-games/kitten-hide-seek.jpeg', external: true, tag: 'tactics', featured: true, description: "Kitten Hide And Seek flips the perspective — you're the kitten (or a tiny protagonist around kitten-sized architecture) and your job is to stay unseen while a larger character patrols the rooms. The cute art direction is the hook but the depth comes from the puzzle side: every room is a different light/shadow setup, and the levels reward memorising patrol paths and using furniture as cover. It is by far the most relaxing game on this page. Good for younger players and a perfect low-pressure break between heavier hide-and-seek rounds.", highlights: ['Cute, kid-friendly art direction', 'Puzzle levels instead of twitch chase', 'Short levels (~3 minutes each)', 'No jumpscares, no time pressure on first playthrough'], controls: [{ keys: 'WASD / Arrows', action: 'Move (with footsteps-on-floor audio)' }, { keys: 'Space', action: 'Pounce to cover' }] },
  { id: 'among-hide-seek', slug: 'among-them-hide-n-seek-2', title: 'Among Them Hide N Seek 2', note: 'Cartoon stealth rounds inspired by maze hiding and chasing.', source: 'GameDistribution', href: gd('012df11266ed40909ce2b303c202fa93'), iframeSrc: gd('012df11266ed40909ce2b303c202fa93'), image: '/imgs/related-games/among-hide-seek.jpeg', external: true, tag: 'companion', featured: true, description: "Among Them Hide N Seek 2 borrows its character silhouettes from the social-deduction hit and wraps them around a chase-round framework: low-poly cartoon interiors, bright color-coding, and a Seeker whose win condition is \"tag everyone before the round timer expires\". The cartoon style keeps it light even when the chase gets tight, and the multiplayer lobbies are where the game actually comes alive. Free browser rounds, no setup, no install — exactly the kind of \"drop in with a friend for one round\" experience that this whole page is built around.", highlights: ['Cartoon low-poly art, very colourful', 'Best in multiplayer (2–8 players)', 'Round timer + tag mechanic, simple rules', 'Great session-game for content creators'], controls: [{ keys: 'WASD', action: 'Move around the map' }, { keys: 'Mouse', action: 'Look / aim direction' }, { keys: 'E', action: 'Vent jump (if your level allows it)' }] },
  { id: 'hunt-and-seek', slug: 'hunt-and-seek', title: 'Hunt And Seek', note: 'Seek-and-find puzzle pacing with hidden characters.', source: 'GameDistribution', href: gd('7fa16181fc5c4ce2a7d3b9a171d48f76'), iframeSrc: gd('7fa16181fc5c4ce2a7d3b9a171d48f76'), image: '/imgs/related-games/hunt-and-seek.jpg', external: true, tag: 'tactics', featured: true, description: "Hunt And Seek is the most puzzle-flavoured game on this page. Instead of a fast tag mechanic, every round is \"find the hidden character in this busy scene\" — like a Where's-Waldo browser game with a 30-second timer and three difficulty tiers per map. Each map is hand-drawn rather than 3D, which keeps the load times low and the rounds crisp. The hidden-object scoring rewards players who scan systematically rather than panic-clicking. It's the best choice on this page when you want a hide-and-seek-adjacent game that exercises your eye rather than your reflexes.", highlights: ['Hidden-object format, Where’s-Waldo style', 'Three difficulty tiers per map', 'Hand-drawn scenes, low GPU demand', '30-second rounds, perfect for time-boxed breaks'], controls: [{ keys: 'Mouse click', action: 'Pick the hidden character in the scene' }, { keys: 'R', action: 'Re-shuffle the scene' }] },
  { id: 'blumgi-slime', slug: 'blumgi-slime', title: 'Blumgi Slime', note: 'A bright precision-jump game for the funny-games strip.', source: 'BlumgiSlime2.io', href: 'https://blumgislime2.io/', iframeSrc: 'https://blumgislime2.io/', image: '/imgs/related-games/blumgi-slime.png', external: true, tag: 'companion', featured: true, description: 'Blumgi Slime switches gears into a one-button precision-jump game: a bright green slime on a black-and-white striped bar, your job is to time the jump so the slime lands on the next platform without rolling off the edge. Same family of platform-jump browser titles (think the Happy Wheels lineage of cute-but-cruel timing games) but stripped down to one mechanic and one rule. Sound simple? It is. Until you reach level 14 and the platforms start shrinking while the camera does the wobble. Free browser play, full-screen capable, no login.', highlights: ['One-button precision-jumping', 'Crisp pink-and-green visual style', 'Levels escalate from slow to frantic', 'Great for quick-win dopamine hits'], controls: [{ keys: 'Space / Click', action: 'Jump' }, { keys: 'Tap-tap', action: 'Double-jump combo' }] },
  { id: 'wacky-steps', slug: 'wacky-steps', title: 'Wacky Steps', note: 'A ragdoll walking challenge with funny fail-heavy movement.', source: 'WackySteps.io', href: 'https://wackysteps.io/', iframeSrc: 'https://wackysteps.io/', image: '/imgs/related-games/wacky-steps.png', external: true, tag: 'companion', featured: true, description: 'Wacky Steps is the easiest game on this page to describe: it is a ragdoll walking challenge. You control a floppy-limbed blocky character, your goal is to take a single step forward, and every part of your body responds to physics — meaning even one mis-timed direction button can send the ragdoll into a faceplant. Each level is a tiny obstacle course, and the fail-then-laugh loop is the entire point. There is no better browser game on this page for streaming clips because every reaction shot writes itself.', highlights: ['Ragdoll physics — every step can become a fail', 'Tiny levels, big comedy', 'Great for streams and reaction content', 'Cute, kid-friendly art'], controls: [{ keys: 'WASD / Arrows', action: 'Each leg / arm independently' }, { keys: 'Space', action: 'Stabilise' }, { keys: 'R', action: 'Reset ragdoll to the start' }] },
  { id: 'hide-me', slug: 'hide-me', title: 'Hide Me', note: 'A mobile-friendly hide-and-seek game about staying unseen.', source: 'GameDistribution', href: 'https://gamedistribution.com/games/hide-me/', iframeSrc: 'https://gamedistribution.com/games/hide-me/', image: '/imgs/related-games/hide-me.jpg', external: true, tag: 'companion' },
  { id: 'escape-again', slug: 'escape-again', title: 'Escape Again', note: 'A short escape-game pick for players who like hiding and searching.', source: 'GameDistribution', href: gd('6ccf5ab92bf4469ea1988aafaba35ca2'), iframeSrc: gd('6ccf5ab92bf4469ea1988aafaba35ca2'), image: gdImg('6ccf5ab92bf4469ea1988aafaba35ca2'), external: true, tag: 'tactics' },
  { id: 'stealth-prison-escape', slug: 'stealth-prison-escape', title: 'Stealth Prison Escape', note: 'Stealth escape action with prison-room pressure.', source: 'GameDistribution', href: gd('2174f17094dd47a4a8eb5cd35bb52f4e'), iframeSrc: gd('2174f17094dd47a4a8eb5cd35bb52f4e'), image: gdImg('2174f17094dd47a4a8eb5cd35bb52f4e'), external: true, tag: 'tactics' },
  { id: 'block-escape', slug: 'block-escape', title: 'Block Escape', note: 'A clean escape puzzle that fits the casual game library.', source: 'GameDistribution', href: gd('9ffaf2fb134844958788642d2f76c6cd'), iframeSrc: gd('9ffaf2fb134844958788642d2f76c6cd'), image: gdImg('9ffaf2fb134844958788642d2f76c6cd'), external: true, tag: 'tactics' },
  { id: 'the-road-home-granny-escape', slug: 'the-road-home-granny-escape', title: 'The Road Home: Granny Escape', note: 'Room-escape horror with hide-and-survive energy.', source: 'GameDistribution', href: gd('1ca550a66423424c98c39fcc8cd57ff0'), iframeSrc: gd('1ca550a66423424c98c39fcc8cd57ff0'), image: gdImg('1ca550a66423424c98c39fcc8cd57ff0'), external: true, tag: 'tactics' },
  { id: 'murder-mystery', slug: 'murder-mystery', title: 'Murder Mystery', note: 'Stealth, logic, and quick decisions in a mystery game shell.', source: 'GameDistribution', href: gd('38d45e35b9c24bd0b6029c1be21f0d05'), iframeSrc: gd('38d45e35b9c24bd0b6029c1be21f0d05'), image: gdImg('38d45e35b9c24bd0b6029c1be21f0d05'), external: true, tag: 'companion' },
  { id: 'hide-ball', slug: 'hide-ball', title: 'Hide Ball', note: 'A light hide-themed puzzle game for quick browser sessions.', source: 'GameDistribution', href: gd('4563680ee85c4a4c8d89744bbb6cff27'), iframeSrc: gd('4563680ee85c4a4c8d89744bbb6cff27'), image: gdImg('4563680ee85c4a4c8d89744bbb6cff27'), external: true, tag: 'companion' },
  { id: 'hide-and-seek-numbers', slug: 'hide-and-seek-numbers', title: 'Hide and Seek Numbers', note: 'Hidden-number search gameplay with a familiar hide-and-seek hook.', source: 'GameDistribution', href: gd('faec2912f8da467aa148d2ab0240e8d7'), iframeSrc: gd('faec2912f8da467aa148d2ab0240e8d7'), image: gdImg('faec2912f8da467aa148d2ab0240e8d7'), external: true, tag: 'companion' },
  { id: 'snake-puzzle-escape', slug: 'snake-puzzle-escape', title: 'Snake Puzzle Escape', note: 'Escape puzzle pacing with compact browser levels.', source: 'GameDistribution', href: gd('504e7fdd353f469b95f1680e4f63b36b'), iframeSrc: gd('504e7fdd353f469b95f1680e4f63b36b'), image: gdImg('504e7fdd353f469b95f1680e4f63b36b'), external: true, tag: 'tactics' },
  { id: 'sneaky-james', slug: 'sneaky-james', title: 'Sneaky James', note: 'A classic sneaking game for stealth-minded players.', source: 'GameDistribution', href: gd('8068c8d940064011b12df676846171e4'), iframeSrc: gd('8068c8d940064011b12df676846171e4'), image: gdImg('8068c8d940064011b12df676846171e4'), external: true, tag: 'tactics' },
  { id: 'agent-zero-infiltration', slug: 'agent-zero-infiltration', title: 'Agent Zero: Infiltration', note: 'Spy-style infiltration for players who like stealth routes.', source: 'GameDistribution', href: gd('f70f024c16204435a4c184523268e57c'), iframeSrc: gd('f70f024c16204435a4c184523268e57c'), image: gdImg('f70f024c16204435a4c184523268e57c'), external: true, tag: 'tactics' },
  { id: 'impostor-among-space', slug: 'impostor-among-space', title: 'Impostor Among Space', note: 'Stealthy impostor play in a space-themed browser game.', source: 'GameDistribution', href: gd('46d0c1a30102462aaf90291f5e0788f4'), iframeSrc: gd('46d0c1a30102462aaf90291f5e0788f4'), image: gdImg('46d0c1a30102462aaf90291f5e0788f4'), external: true, tag: 'companion' },
  { id: 'metro-escape', slug: 'metro-escape', title: 'Metro Escape', note: 'A contained escape game for puzzle-search players.', source: 'GameDistribution', href: gd('1e58c5988fb44962a4cd120615d1ca6a'), iframeSrc: gd('1e58c5988fb44962a4cd120615d1ca6a'), image: gdImg('1e58c5988fb44962a4cd120615d1ca6a'), external: true, tag: 'tactics' },
  { id: 'bus-jam-escape', slug: 'bus-jam-escape', title: 'Bus Jam Escape', note: 'A compact escape puzzle with fast visual scanning.', source: 'GameDistribution', href: gd('06603b27a3824932aa3b23e94ef310e7'), iframeSrc: gd('06603b27a3824932aa3b23e94ef310e7'), image: gdImg('06603b27a3824932aa3b23e94ef310e7'), external: true, tag: 'companion' },
  { id: 'red-light-green-light', slug: 'red-light-green-light', title: 'Red Light Green Light', note: 'Stop-and-go survival tension, good for party-game users.', source: 'GameDistribution', href: gd('788f89d325d840f391139ce0e1212c46'), iframeSrc: gd('788f89d325d840f391139ce0e1212c46'), image: gdImg('788f89d325d840f391139ce0e1212c46'), external: true, tag: 'companion' },
  { id: 'isometric-escape-2', slug: 'isometric-escape-2', title: 'Isometric Escape 2', note: 'Room-search puzzle play with an isometric escape layout.', source: 'GameDistribution', href: gd('aada1dda0c9f404187438b121d48b644'), iframeSrc: gd('aada1dda0c9f404187438b121d48b644'), image: gdImg('aada1dda0c9f404187438b121d48b644'), external: true, tag: 'tactics' },
  { id: 'first-day-of-school', slug: 'first-day-of-school', title: 'First Day Of School', note: 'Light casual play for the softer side of the library.', source: 'GameDistribution', href: gd('7a816be3e2ca41a5b97a85cd02e819c8'), iframeSrc: gd('7a816be3e2ca41a5b97a85cd02e819c8'), image: gdImg('7a816be3e2ca41a5b97a85cd02e819c8'), external: true, tag: 'companion' },
  { id: 'mystic-object-hunt', slug: 'mystic-object-hunt', title: 'Mystic Object Hunt', note: 'Hidden-object searching for users who like seek-and-find loops.', source: 'GameDistribution', href: gd('3e1ae43e7f754aaebf3b8d7c134eb1f9'), iframeSrc: gd('3e1ae43e7f754aaebf3b8d7c134eb1f9'), image: gdImg('3e1ae43e7f754aaebf3b8d7c134eb1f9'), external: true, tag: 'companion' },
  { id: 'hidden-object-my-hotel', slug: 'hidden-object-my-hotel', title: 'Hidden Object: My Hotel', note: 'Hidden-object cleanup and search gameplay.', source: 'GameDistribution', href: gd('26b8b04411e84591b2afc276ce177c37'), iframeSrc: gd('26b8b04411e84591b2afc276ce177c37'), image: gdImg('26b8b04411e84591b2afc276ce177c37'), external: true, tag: 'companion' },
  { id: 'the-last-survivors', slug: 'the-last-survivors', title: 'The Last Survivors', note: 'A two-character survival puzzle game with escape pressure.', source: 'GameDistribution', href: gd('8156e4c8e28e4425befb8d969759dd48'), iframeSrc: gd('8156e4c8e28e4425befb8d969759dd48'), image: gdImg('8156e4c8e28e4425befb8d969759dd48'), external: true, tag: 'tactics' },
  { id: 'wild-hunting-clash', slug: 'wild-hunting-clash', title: 'Wild Hunting Clash', note: 'A hunting pick for users browsing seeker-style games.', source: 'GameDistribution', href: gd('0143ede05b904e3db4add3645b0ef415'), iframeSrc: gd('0143ede05b904e3db4add3645b0ef415'), image: gdImg('0143ede05b904e3db4add3645b0ef415'), external: true, tag: 'companion' },
  { id: 'mr-hunter', slug: 'mr-hunter', title: 'Mr. Hunter', note: 'A simple hunter game for the seeker side of the collection.', source: 'GameDistribution', href: gd('34d7ae0bb0504cf092c023abec4b08ed'), iframeSrc: gd('34d7ae0bb0504cf092c023abec4b08ed'), image: gdImg('34d7ae0bb0504cf092c023abec4b08ed'), external: true, tag: 'companion' },
  { id: 'zombie-hunter-survival', slug: 'zombie-hunter-survival', title: 'Zombie Hunter Survival', note: 'Survival action for users who click into hunter games.', source: 'GameDistribution', href: gd('1b9f209b5035470fa61e8c4d97ed94dd'), iframeSrc: gd('1b9f209b5035470fa61e8c4d97ed94dd'), image: gdImg('1b9f209b5035470fa61e8c4d97ed94dd'), external: true, tag: 'companion' },
  { id: 'pou', slug: 'pou', title: 'Pou', note: 'A recognizable casual game for broader funny-game browsing.', source: 'GameDistribution', href: gd('d1362abc246f43bdb5c26643aec2b61b'), iframeSrc: gd('d1362abc246f43bdb5c26643aec2b61b'), image: gdImg('d1362abc246f43bdb5c26643aec2b61b'), external: true, tag: 'companion' },
  { id: 'childcare-master-online', slug: 'childcare-master-online', title: 'Childcare Master Online', note: 'A casual baby-care pick near the Baby Hide and Seek audience.', source: 'GameDistribution', href: gd('ac3e4bc439294078a71f3409721dd5ad'), iframeSrc: gd('ac3e4bc439294078a71f3409721dd5ad'), image: gdImg('ac3e4bc439294078a71f3409721dd5ad'), external: true, tag: 'companion' },
  { id: 'kindergarten-dress-up', slug: 'kindergarten-dress-up', title: 'Kindergarten Dress Up', note: 'A kid-friendly casual game for the soft recommendation shelf.', source: 'GameDistribution', href: gd('8b9ff8550d3642a2a148116b7ec486a8'), iframeSrc: gd('8b9ff8550d3642a2a148116b7ec486a8'), image: gdImg('8b9ff8550d3642a2a148116b7ec486a8'), external: true, tag: 'companion' },
  { id: 'snow-white-pregnancy', slug: 'snow-white-pregnancy', title: 'Snow White Pregnancy', note: 'A casual browser title for extra library depth.', source: 'GameDistribution', href: gd('2c6a5422029344caa4001928b002e7e3'), iframeSrc: gd('2c6a5422029344caa4001928b002e7e3'), image: gdImg('2c6a5422029344caa4001928b002e7e3'), external: true, tag: 'companion' },
  { id: 'baby-hazel-new-born-baby', slug: 'baby-hazel-new-born-baby', title: 'Baby Hazel New Born Baby', note: 'A known casual baby game for broader recommendations.', source: 'GameDistribution', href: gd('3d3dfa7a60904519b4be9fbe555920e3'), iframeSrc: gd('3d3dfa7a60904519b4be9fbe555920e3'), image: gdImg('3d3dfa7a60904519b4be9fbe555920e3'), external: true, tag: 'companion' },
  { id: 'packing-line', slug: 'packing-line', title: 'Packing Line', note: 'A quick sorting puzzle for the long scroll game shelf.', source: 'GameDistribution', href: gd('b7c6b58e8a0841f984c2be418d3299d4'), iframeSrc: gd('b7c6b58e8a0841f984c2be418d3299d4'), image: gdImg('b7c6b58e8a0841f984c2be418d3299d4'), external: true, tag: 'companion' },
];

export function getRelatedGameBySlug(slug: string) {
  return relatedGames.find((game) => game.slug === slug);
}

export function getFeaturedRelatedGames() {
  return relatedGames.filter((game) => game.featured);
}
